fixed ws version, since 3.x doesn't work
ws 3.x crash on connect with:
websockify.js:129
        callback(true, 'binary');
        ^

TypeError: callback is not a function